### ISSUE TITLE
LLVM bindings - possible extraction? (and licensing)

### ISSUE THREAD

**Issue by luislavena** [runic-lang/compiler#1]
Hello!

With a little bit of shame I will admit I've been stalking your work 😊 

Peaked at the source code and noticed you have LLVM bindings. Have you considered put them as a separate shard?

On that subject, noticed you used CeCILL license, which mean, even if you release those as a shard, will infect any program that uses it (from CeCILL own [FAQ](http://www.cecill.info/faq.en.html#bonne))

In case if is not possible, perhaps you can provide some indications on how the bindings were created (looks like most were automatically generated, but not sure).

Thank you in advance for your time and your responses.

Have a nice day! 😄

**Comment by ysbaddaden** [comment]
Duh, I knew I should have kept it private :wink: 

LLVM bindings are autogenerated, and don't do anything more like wrapping the underlying C types, except for the nice `LLVM.init_xxx` macros. There would be no value to publish them separated, in fact they should be dropped eventually, and generated on-the-fly... because the real deal is the automatic generator, that I should publish.

About the license, please note that I specifically chose the [CeCILL-C](http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html) license, as per the [FAQ](http://www.cecill.info/faq.en.html#differences):

> If you distribute a program that is a modification of a program under one of the licenses in the CeCILL family, or that incorporates such a program, totally or partially (...) If the program is under CeCILL-C, you can also distribute your program under any license but you have to distribute under CeCILL the possible modifications you did to the original source code (and mention the use you made of the initial program).

**Comment by luislavena** [comment]
> There would be no value to publish them separated, in fact they should be dropped eventually, and generated on-the-fly... because the real deal is the automatic generator, that I should publish.

![](https://media.giphy.com/media/sDcfxFDozb3bO/giphy-downsized.gif)

😁 

Even that is low-level, is good to start 
> About the license, please note that I specifically chose the CeCILL-C license, as per the FAQ

Might need to show that license to my lawyer, AFAIK using that library in a non-OSS might be forced to open-source it's code.

Thank you for taking the time and responding my questions.

Have a nice day!

**Comment by ysbaddaden** [comment]
Basically:
- The CeCILL license is GPL-like (IMHO good for final apps).
- The CeCILL-C license is LGPL-like (IMHO good for libraries, with due credits and redistribution of changes).
- The CeCILL-B is BSD-like: whatever, just give credit.

**Comment by ysbaddaden** [comment]
Published: https://github.com/ysbaddaden/clang.cr
